### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by krainboltgreene** [bikeright/app#1]
## Stories
- [ ] As a user I can register my bike so that others can look up my bike
- [ ] As a user I can look up a bike so that I can find owners of stolen bikes
- [ ] As a {role} I can {function} so that {role}
